### ISSUE TITLE
Knapper kun synlig når brukerene er aktiv

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#12]
Knappene kan gjøres synlige kun når brukeren er aktiv på nettsiden. Ved inaktivitet forsvinner disse knappene slik at presentasjonsvisningen kun viser tavla med avganger. 

<img width="1130" alt="Screenshot 2020-06-18 at 14 31 22" src="https://user-images.githubusercontent.com/67003841/85020401-93106480-b170-11ea-8616-9410b26c2ae2.png">

**Comment by draperunner** [comment]
Kanskje eg misforstår, men dette er allerede implementert ved å detektere om muspeikaren er på sida. Om du flyttar muspeikaren ut av vinduet forsvinn tilbakepil, "Endre visning" og "Rediger tavla".

**Comment by rosvik** [comment]
Vi snakket om å gjøre størrelsejustering av boksene tydligere (#10) så da bør disse også skjules. 

Også mulig å ha en timeout slik at elementene skjules når man ikke er aktiv etter en liten stund. Hvis jeg forstår det riktig så er det kun om musepekeren forlater vinduet, at det skjer nå.

**Comment by rosvik** [comment]
Dette har blitt fikset upstream nå
