### ISSUE TITLE
Utnytte mer av bredden ved mobil-visning

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#13]
Mobilvisningen er i dag for smal i forhold til skjermen. Man kan med fordel gjøre tavla bredere ved smal skjerm, for å utnytte plassen bedre.

<img width="392" alt="Screenshot 2020-06-18 at 14 35 50" src="https://user-images.githubusercontent.com/67003841/85020712-0914cb80-b171-11ea-8d8d-33d21452b986.png">

**Comment by rosvik** [comment]
https://github.com/entur/tavla/pull/159
