### ISSUE TITLE
Redigeringsknappene skal ligge foran kolonnene på mindre skjerm

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#14]
Så fort man gjør skjermen smalere legger knappene seg bak tavla. Det gjør de lite tilgjengelige. Legg disse foran tavla. 

<img width="1070" alt="Screenshot 2020-06-18 at 14 44 14" src="https://user-images.githubusercontent.com/67003841/85021544-462d8d80-b172-11ea-9d69-d624224afcd6.png">

**Comment by rosvik** [comment]
Kommer til å bli fikset av planlagte brukergrensesnittforandringer.
