### ISSUE TITLE
Mobilvennlige redigeringsknapper

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#15]
Ved mobilvisning blir plassen redusert. Lag en knapp som inneholder både "Endre visning" og "Rediger tavla"-knappene. 

<img width="441" alt="Screenshot 2020-06-18 at 14 53 47" src="https://user-images.githubusercontent.com/67003841/85022443-9822e300-b173-11ea-96fc-8d032fc532fe.png">

**Comment by draperunner** [comment]
Me planlegg å redesigne dette heilt. Det blir ein heilt ny meny sentrert på botnen av sida. Me må sikre at denne er mobilvennlig.

Uferdig skisse:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/4339443/85123654-eba33880-b228-11ea-803c-4c39f6e83755.png">
