### ISSUE TITLE
Samle busslinjer og tydeliggjøre ulike retninger 

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#16]
De fleste bussholdeplassene har busslinjer som går i to retninger. Det er vanskelig å forstå om bussene går fra samme eller motsatt side av vegen slik dagens tavle visualiserer avgangene. Prøv å komme opp med et nytt design som gjør det enklere å skille ulike retninger. 

<img width="865" alt="Screenshot 2020-06-18 at 15 01 23" src="https://user-images.githubusercontent.com/67003841/85023119-9a397180-b174-11ea-9660-b49571ada6ed.png">

**Comment by rosvik** [comment]
Kanskje #54 er med på å forbedre dette?
