### ISSUE TITLE
Markere sanntid i gult

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#26]
Fargekode Gul: EAD465 

![Screenshot 2020-06-25 at 11 44 03](https://user-images.githubusercontent.com/67003841/85696405-344f6b80-b6d9-11ea-9418-0c62ea9e77ac.png)

**Comment by rosvik** [comment]
Nytt forslag: Skrive 'ca.' forran tider som _ikke_ er sanntid.

![Screenshot 2020-08-04 at 15 05 43](https://user-images.githubusercontent.com/1774972/89297436-1f64e100-d664-11ea-9702-39e2bde41137.png)
