### ISSUE TITLE
Lik farge på sykkelikon

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#3]
Sykkelikonene må ha lik farge innad i hver kolonne. Endre slik at alle er grønne.

![Screenshot 2020-06-18 at 11 23 58](https://user-images.githubusercontent.com/67003841/85003800-fb524c80-b156-11ea-94dc-d1b3b94e1508.png)

**Comment by Martinbmoller** [comment]
Sykkelikonene må ha lik farge innad i hver kolonne. Endre slik at alle er grønne.

![Screenshot 2020-06-18 at 11 23 58](https://user-images.githubusercontent.com/67003841/85003642-c514cd00-b156-11ea-962e-f358bcf603da.png)

**Comment by rosvik** [comment]
Potensielt fikset av https://github.com/entur/tavla/pull/150

**Comment by rosvik** [comment]
Burde denne kanskje vært i en annen farge enn grå? Grønnfargen var kanskje bedre?
