### ISSUE TITLE
Alignment av tilbakepila

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#4]
Pila må alignes slik at tuppen av pila er på linje med ytterkanten av ytterste kolonne. 

![Screenshot 2020-06-18 at 11 40 32](https://user-images.githubusercontent.com/67003841/85005067-97c91e80-b158-11ea-8c87-9c281fa6ab34.png)

Vertikalt skal pila stå i sentrert i redigeringsknappene.

![Screenshot 2020-06-18 at 11 38 55](https://user-images.githubusercontent.com/67003841/85005113-a6afd100-b158-11ea-9849-8dcdbe150183.png)

**Comment by rosvik** [comment]
https://github.com/entur/tavla/pull/158
