### ISSUE TITLE
Entur-lilla bilde vises hvis Tavla ikke finner avgangssteder i nærheten

### ISSUE THREAD

**Issue by torfjor** [AtB-AS/tavla#52]
<img width="1050" alt="Screenshot 2020-08-06 at 15 52 58" src="https://user-images.githubusercontent.com/13596984/89540178-fd529680-d7fc-11ea-9ac6-4e9048d5671a.png">

Kanskje vi skulle ha noe AtB-farget her?

**Comment by rosvik** [comment]
Et greit testcase for å få feilmeldingen er "Killingdalsvegen, Holtålen"
