### ISSUE TITLE
Bedre kontrast på trikk og tog-ikon

### ISSUE THREAD

**Issue by Martinbmoller** [AtB-AS/tavla#7]
For dårlig kontrastene mellom bakgrunnsfarge og trikk og tog-ikonene gjør de lite synlige. Lysere nyanser av lilla og blå vil bedre kontrasten.  

![Screenshot 2020-06-18 at 12 35 50](https://user-images.githubusercontent.com/67003841/85010429-4886ec00-b160-11ea-88b8-33202a44dfb4.png)

**Comment by rosvik** [comment]
Fikset av https://github.com/entur/tavla/pull/150
